### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by liqianjiang** [dengshiwei/asm-module#1]
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.andoter.plugin:ASMPlugin:1.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/andoter/plugin/ASMPlugin/1.1/ASMPlugin-1.1.pom
       - https://jcenter.bintray.com/com/andoter/plugin/ASMPlugin/1.1/ASMPlugin-1.1.pom

需要添加额外仓库的配置吗

**Comment by andoter0501** [comment]
@liqianjiang 这个工程是数据中的示例代码，都是 Java 工程可以直接运行,不需要添加额外的仓库配置.
[asm-example](https://github.com/dengshiwei/asm-example) 是一个结合 Android Gradle 的工程，需要你先把插件发布到本地，然后在引用就行了。
